### ISSUE TITLE
Update points value -> WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by frjariello** [ham-systems/temperature-map-gl#3]
Hi, first, very thanks for sharing your great work. 
I would like to be able to update the graph when the temperature values change, or in any case every few minutes, so from the html I recall your js again, but I have two problems connected to each other. The first is that the written values overlap, and the second, (more important) is that after about ten updates in the console I have _WARNING: Too many active WebGL contexts. Oldest context will be lost._ I tried to figure out how to handle it, with loseContext / restoreContext, but unfortunately I couldn't. Can you help me? Thanks anyway.

**Comment by ekchatzi** [comment]
@frjariello doesn't the method `set_points` followed by a `draw()` work for updating the values? 

it shouldn't create more WebGL contextes. It should just update the one it already has.

**Comment by frjariello** [comment]
Hi, yes you are right, calling set_points and then draw works perfectly 🙂 Thanks!
